AI-141: Update boilerplate
peerpower/nestjs-boilerplate pull request #1
Opened 2022-04-18 08:15 UTC by nopasuts

2022-04-19 05:33 UTC, chawaponake requested changes

2022-04-19 05:33 UTC, chawaponake commented on package.json
> +        "pp-stark-industries": "../stark-industries",
อันนี้ผิดรึเปล่านะ

2022-04-19 05:58 UTC, nopasuts commented on config.yaml.example
> +AIRTABLE_API_KEY: null
Removed krub

2022-04-19 05:59 UTC, nopasuts commented on config.yaml.example
> +DB_HOST: 'db'
Fixed krub

2022-04-19 05:59 UTC, nopasuts commented on src/main.ts
> +    // setupSwagger(app);
Fixed krub
แก้ alias ของ swagger แล้ว สามารถใช้งานได้ปกติแล้วครับ

2022-04-19 06:00 UTC, nopasuts commented on package.json
> +            "@swagger/(.*)": ">rootDir>/swagger/$1"
Fixed krub

2022-04-19 06:00 UTC, nopasuts commented on package.json
> +        "pp-stark-industries": "../stark-industries",
Fixed krub

2022-04-19 12:26 UTC, chawaponake requested changes

2022-04-19 12:26 UTC, chawaponake commented on package.json
> +        "dotenv": "16.0.0",
ไหนๆก็ไม่ใช้แล้วฝากลบหน่อยนะครับ

2022-04-19 12:26 UTC, chawaponake commented on package.json
> +        "passport-jwt": "4.0.0",
น่าจะไม่ได้ใช้เนอะ ฝากลบพวกนี้ด้วยนะ

2022-04-20 08:35 UTC, chawaponake approved these changes

2022-04-20 08:36 UTC, merged